### PR TITLE
Code cleaning, refactoring improvements etc.

### PR DESCRIPTION
**Pull request by Johndeep**
= On the surface =
* Implemented NumberPicker.
* All preferences should now be initialized at the beginning, also at fresh start.
* The preferences now auto update summary description.
* Kissmanga and MangaPanda got some nicer title formatting.
* Coloring and design are a little improved.
* Many little things or "Papercuts" were fixed.
* restructured main menu, added "About" section in preferences
* nicer look of License view (but this will be changed again later)

=  Under the hood =
* Mostly code cleaning and reformatting (therefore the very big number of changes. For this, I finally added the codeStyleSettings.xml, it helps you with reformatting in a nice and readable style automatically).
* Some little code optimizing.
* Re-factored some Spanish variable names to English for better reading.
* Re-factored and reordered variables for better overview.

Please review this, even if I tested it very much, this is one of these bigger changes.

### CODE REVIEW

**Comment by Johndeep** [comment]
Here we are, another really huge pull request.
Please have a look. Now I'll sit back and watch.

**Comment by raulhaag** [comment]
i read the code, i go to test

**Comment by raulhaag** [comment]
reading preferences i found a misunderstanding
maximun number of retries per chapter -> realy is error tolerance per chapter (number de images who can't be downloaded before stop the download) 
example: if  = 1 when an image has exhausted its retries per image and marked as error the chapter download go to stop.
other thing i can see is the option hide readed, thi was in a submenu to see its description, this way the icon don't show clicked in app start (if selected)

on the reader keep_on (now changed to keep_screen_on)
     Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
            at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:261)
            at ar.rulosoft.mimanganu.ActivityLector.onCreate(ActivityLector.java:112)
the previus version use integer to save this you need to change the tag if you want to do this (in this case is almos irrelevant but in other is beter try to keep olds configuration)
licence looks good also added version i go to keep testing while i add a new function

**Comment by raulhaag** [comment]
Problem importing style:
Cannot read scheme codeStyleSettings.xml  from '$ROOT_CONFIG$/codestyles': Argument for @NotNull parameter 'name' of com/intellij/psi/impl/source/codeStyle/CodeStyleSchemeImpl.<init> must not be null

i sugest to use android default 
https://github.com/android/platform_development/blob/master/ide/intellij/codestyles/AndroidStyle.xml

**Comment by Johndeep** [comment]
I thought so, I really didn't understand the error tolerance option.. sorry ^^"
Maybe I should take a look into the class and see if I can apply your explanation.

About the "hide read", I would really like it, if I can switch between them with just one click. Instead, I put the settings into the drop down menu, I wanted to put the download button into it too, but not now.

If you want to see the description, you have to hold the button a while, then a description will pop up.

What why? Integer and Boolean error? I thought I made sure to prevent that.. because if you only toggle them on and off, why Integer? I would instead fix it all over instead of going back to Integer. Can you tell me, where this error happens?

Sorry, but I also made some modification in activityManga, because I had to add some stuff too.. but while I was at it, I wanted to clean up a bit, for better understanding in the future. Sorry if I made it complicated for you.. ^^"

And the code styling.. okay, it's really the best, if we use the same code style, I'll use AndroidStyle.xml in the future.

**Comment by Johndeep** [comment]
And sorry, if there is some file missing after this merge, somehow the gitignore in AndroidStudio is not applied and I forgot to un-tick the changes..

**Comment by raulhaag** [comment]
Reading direction is managed from the ordinal, go back to the original order (the enumerated values are saved as integer)

**Comment by Johndeep** [comment]
Wait, reading direction? Somehow I remember I didn't modify this.., I did change the type once of "keep_screen_on" to boolean though, but when did I change direction..? I dunno..

**Pull request merged**
