### PR TITLE
[WIP] fixes for MangaHere

### PR DESCRIPTION
**Pull request by tempura-san**
Proposed fixes for #499.

### CODE REVIEW

**Comment by raulhaag** [comment]
@tempura-san  i added the db changes to allow save the path as you propone, check last commit if you want to change all values on db from mangahere to relative path you need to use the last update from db changing the replace 'http://www.mangahere.cc' to '' and update the server to manage this

**Comment by tempura-san** [comment]
Thank you - I have adapted MangaHere and added the removal of protocol and host for the database upgrade. Please take a look at the changes. Also I added some other checks for MangaHere.

The `TestServersCommon` now issues a warning in case the path is not relative.

BTW while we are at it: wouldn't the same thing as was now discussed for chapters apply to the Manga as well? The benefit would always be to be able to simply switch hosts in case of need. At least Manga and chapter pages are always hosted by the pages themselves (for images this does not hold true).

**Comment by raulhaag** [comment]
merging, but i'm not so conviced about use the URL onky to get the path iknow it more elegant but to many objects creation only for get the path if you think in all the sites its is used

**Comment by raulhaag** [comment]
@tempura-san about other thing, what do you think about the branch testdoublebar?

**Comment by tempura-san** [comment]
I see you have replaced the URL stuff by regular expressions - in the end it doesn't matter much I guess, nonetheless I do not believe the overhead to be of much relevance.

Concerning your second question: well, I might be biased, as I'm already quite used to the UI - I personally like the single bar solution (only one at the top) better.

Reason: On my device (Nexus 7 2012) the bottom bar becomes way too big and has thus a strong visual impact. And it also takes away screen space.
Even the [Material design guidelines for toolbars](https://material.io/guidelines/layout/structure.html#structure-toolbars) show more than one icon in the top toolbar - so it is definitely acceptable.

Maybe on a small screen device it might look different or cluttered, but I do not have a phone running Android, so I can't test this...

**Comment by tempura-san** [comment]
If I may say - I like the idea in #221 better if you wan't to improve on the UI... :smile:

**Pull request merged**
