### PR TITLE
Crash Reports + small improvements 

### PR DESCRIPTION
**Pull request by xtj-9182**

### CODE REVIEW

**Comment by raulhaag** [comment]
tell me more about acra just about user interation whit its and what kind of info it give to our and what its take from user (user privacy), and the login need a mail

**Comment by xtj-9182** [comment]
user interaction should be minimal, ACRA will try to send a report after a crash happens. I'm going to write you a pm with the login details with that you can also check my Test Issue regarding information that will be send (select develop version and closed issues), as far as I understand it no Personal Identifying Information is send, However we can still fine tune what kind of information is send see: https://github.com/ACRA/acra/wiki/ReportContent, by default we don't send all of that.

**Comment by raulhaag** [comment]
ok lets try it for a couple of months if users acept it, write me to raghaag on gm

**Comment by xtj-9182** [comment]
ok so I added you as raghaag@gmail.com

I don't think user will even notice this, right now when a crash occurs we simply send a crash report, this happens with no user interaction at all currently, so user will still get the typical "force close" dialog. (we can improve this in the future and add like a custom activity that we display once a crash occurs)

We do however NOT send any Personal Identifying Information, all we send is a stacktrace + some hardware information like what device someone used. So for example when it crashes on my LG G3 it will look like every other LG G3.

**Comment by Dostoi** [comment]
What happens if there's no connection at the time of crash ?

**Comment by xtj-9182** [comment]
ACRA writes a crash report to local storage (it's /data/data/ar.rulosoft.mimanganu/ on my device) and next time you start MiMangaNu ACRA will try to send the report.

**Pull request merged**
