### PR TITLE
List view improve

### PR DESCRIPTION
**Pull request by Johndeep**
Okay, sorry if I had to close the #99 patch, Github just recommended me to make another pull request.. whatever..

With this..
* Database path is untouched again, just made some tiny little changes.
* Lazylist or the entire for files were merged to three and I cleaned up quite a bit. I found out, that especially the Memory Cache of this lib can cause some crashes, but I didn't touched it yet. I would recommend to use the default lruCache from Android itself. But that for another time.
* Bit change are the colorPicker and Directory browser. I almost completely revamped them! For once, the directory look and feel is much more like standard apps nowadays and has even alternating list colors, well, just some fun I implemented, of course, delete three lines and then no alternating.
* The colorPicker on the other hand should replace the entire colorpickercollection, I even made some effort and named all the colors. Also I made use of as much Android standard stuff without re-write too much code. So that's the result.

I hope you like this change.

### CODE REVIEW

**Comment by Johndeep** [comment]
With this, you can theoretically remove the colorpickercollection, except you still need something from it.
And again, the database behaves like before, only code formatting (by hand) changes were done.

**Comment by raulhaag** [comment]
dir selector look good and the picker, just a couple of fixes (changed keys from primario and secundario, for retrocompat)

**Comment by Johndeep** [comment]
why change key? retro compatibility? As far as I saw, there were no other usages of colorpickercollection.. and to be honest, I really do not like the colopickercollection.
Well, that aside, if you need some other colorpicker, I can write them. After finally understanding how DialogPreference and other stuff works, it's easy to do more than just this.

**Comment by raulhaag** [comment]
Old Color picker save the color as int value not the index, then index out
of bounds when you try to run reader color in as index

**Comment by Johndeep** [comment]
Hmm, I thought by using index, the defaulting will be easier ("3", "5", "9"), but if you need something like ("0xFF223344", "0xFF227732"), then okay, I can change that, give me some time and you'll get your color int value.

**Comment by raulhaag** [comment]
voy a escribir en español ya que a veces no me explico muy bien en ingles, solo decía que creando una nueva claves era suficiente y no tenias que cambiar nada pero ahora que lo modificaste para que guardara el valor y tomaran los antiguos sin dar error mejor

**Comment by Johndeep** [comment]
Hmm sorry, I will try to use more simple English.
Last Patch #103 makes ColorPicker save absolute values ("-16273846" "-384956") like always again.
Like you said, makes error searching easier, right?

**Comment by raulhaag** [comment]
Inglés entiendo perfectamente el problema es cuando tengo que yo escribir a veces no l me expreso bien.
Acerca del error que hablaba en la versión anterior      con la librería externa de selección de color los guardaba como el valor entero,  y si la nueva trataba de buscar ese valor -12345667 daba un error de fuera de indice, yo no me explique bien en el momento pero decía que al cambiar las claves por nuevas era suficiente pelo ahora que se puede conservar las antiguas mejor.

**Comment by Johndeep** [comment]
Hmm, sorry, googletranslate doesn't help much.
In summary, index values did cause errors, but the absolute values did not.. I still don't know _**where**_ the problems happened though.

**Pull request merged**
