### PR TITLE
Translateable filters and server cleanup

### PR DESCRIPTION
**Pull request by tempura-san**
I have opened this pull request to visualise my progress on cleaning up the server classes with respect to:

- reuse pattern
- filter translations
- warning removal
- deprecated functions removal

I would continue to fixup at least the English servers, as matching genres is quite simple for them (my Spanish is not that proficient), so I would keep pushing to this pull request.

Other work done in the commits:

- newlines are no longer removed from the fetched HTML, resulting in better readable summaries
- to counter the first fix, all regular expression matches are now done using `Pattern.DOTALL` to match across lines
- NineManga based servers: the common code has been refactored to a base class, so that language specific parts can be overridden in subclasses
- filter button is now hidden if the server filter list is empty
- Android Studio related warning removals
- added a load of strings to translate :smile: 

@raulhaag Of course you can merge this anytime you want. I would then continue and raise another pull request then. I plan to get one server per evening, so one more week should be sufficient.

### CODE REVIEW

**Comment by raulhaag** [comment]
Merging, that look like lot of work, thanks.

**Comment by tempura-san** [comment]
You're welcome. Hopefully I haven't introduced any bugs... :smile:

**Comment by tempura-san** [comment]
@raulhaag Please do not push this yet to a release! I have just noticed that NineManga seems to have some detection for non-authorized apps? Seems they only want to support Manga Dogs and loading of images fails.
This could be related to some cleaup I have done - so give me a little time.

Sorry for the inconvenience.

**Comment by tempura-san** [comment]
This might be related to #462. It seems, that NineManga (and all subdomains) introduced a detection in case an ("unauthorized") app wants to fetch images from their server. In case this is detected, the main image is replaced with [this warning](http://es.taadd.com/files/img/57ead05682694a7c026f99ad14abb8c1.jpg).
This image's URL does not match the regular expression for the image detection and the error message is displayed.

First I thought it was part of my rework, but I have just tested 1.71 and it fails, too. So the pull request is okay. The additional headers added before my rework change nothing.

Nonetheless NineManga is broken for now. I wanted to check the Manga Dogs app, but it fails to install on my Nexus 7 (not supported). Besides, according to the comments Mangs Dogs if quite crappy and more of an adware than a reader.

It would be interesting which header information is sent by the app - this could then be replicated in MiMangaNu. At least until the next change. Would become some kind of cat and mouse game if they insist.
The alternative would be to drop support for NineManga (and it subdomains) from MiMangaNu.

**Pull request merged**
