### PR TITLE
some fixes and rework after testing

### PR DESCRIPTION
**Pull request by tempura-san**
Hi @raulhaag - after a long time, I had a little time to play again with MMN. :smile:
In this PR, there are all the fixes I have made after running the unit tests. It is a mixture of warning removals, deprecation removals and functional fixes. I tried to keep the commits small, so they are easy to review. Hope it is of help.
Cheers! :beer:

### CODE REVIEW

**Comment by raulhaag** [comment]
hi, nice to read you againg ;-) and thanks to you for the help 👍, merging

**Comment by borrougagnou** [comment]
Why "disable japscan" ?

**Comment by tempura-san** [comment]
@borrougagnou Only the host based unit tests are disabled as the servers need `duktape` to work, which can be tested only on a device (or emulator) due to JNI availability. So no need to worry.
@raulhaag You're - as always - welcome. Thank you for your ongoing work!

**Comment by borrougagnou** [comment]
@tempura-san  hmmmm I would like to help you but I don't really understand what you say ^^"
I'm beginner on JAVA although I can do it on my own (like the unscramblor I created, see #617

**Comment by tempura-san** [comment]
@borrougagnou Nevermind - I'm not a Java expert myself by far (usually I program mostly C and Python).
What I meant is, that for the unit tests (automated testing of some common issues and regressions for every server backend) there are two kinds: **host based tests**, which are run on the development machine directly (via a Java virtual machine) and **instrumented tests** which are run on either the target device or an emulator.
Host based tests can be iterated a bit faster and do not need a device or emulator running (for example, I cannot run the Android emulator on my Lenovo T400, as its CPU is missing some required features for the emulation). So I prefer host based tests, so I do not have to go and look for the (proprietary) data cable of my ASUS TF701T :smile:. But some servers (like JapScan and MangaShiro) make use of the ˋduktapeˋ library, which is programmed in C and is only available for testing in a real or emulated Android environment. This is because of the need for JNI (Java native interface), which is the glue between the C library and the Java runtime.
Therefore there are two sets of test suites (Robolectric based on the development host and instrumented), where some server tests are ignored for the host portions, and are only executed when run instrumented.
Nonetheless I prefer to keep all servers present in both configurations for the sake of completeness - I just disable the ones, which cannot be run on the host, so that they are only tested via instrumentation (which can always test everything).
I hope this sheds some light on the issue, but take it with a grain of salt. This is just my self-taught knowledge. :smile:
Cheers

**Pull request merged**
