### PR TITLE
One big update

### PR DESCRIPTION
**Pull request by Johndeep**
This summarizes and improves the two Pull Requests from yesterday, therefore I closed the previous two.

- Replace StarKana with MangaReader.net (which is almost identical to MangaPanda, but why not)
- Fix KissManga (remove dependency of IP Address, improved or just fixed search function)
- several import improvements, thanks to Android SDK Studio auto stuff
- translation fixes and improvements (german and french)

### CODE REVIEW

**Comment by Johndeep** [comment]
I hope this won't interfere into the original too much (one revert to original is referring to the app.iml file, whatever it does)

**Comment by raulhaag** [comment]
read the code, only 2 things to mod don't remove old servers for compatibility reason and add a new index for the new server i will do it don't worry

**Comment by Johndeep** [comment]
Okay, sorry if I overwrote StarKana, next time I'll be more careful.
Oh, and also sorry, if somehow the comments of the commit are now a big mess, it's because I reformat stuff (reorganize imports and what Android Studio offers to you) and tried to make things cleaner or clearer.

**Comment by raulhaag** [comment]
don´t worry in a couple of minutes a will upload the last version 1.31 whit the corrections and your contributions

**Comment by Johndeep** [comment]
Yay! Now I have to figure out, how to sync my fork with yours, because there are still much to do (i.e. dark theme or some open issues, which would be great to get that fixed too).

Anyway, maybe today I can finally go on reading my stuffs, thanks ;P

**Pull request merged**
