### PR TITLE
Integrate TravisCI

### LINKED ISSUE #129: Having beta/alpha release
As you asked for help to test the app, I was thinking that it may be a good idea to have beta/alpha (call it like you want) release.
This way people will know that it's buggy but can easily help you.
Kind like what F-droid is doing with it's app. Look at it in the f-droid app. It's written 0.97-alpha6 for the last one.

### PR DESCRIPTION
**Pull request by null-dev**
Ok, people have been asking for alpha/beta builds so here is a build every commit :+1: (Fixes #129 )!

This commit will allow travis to automatically make a new build every time the code in the repository is changed.

This does require however, that the owner of this repo (raulhaag) login into http://travis-ci.org/ and enable builds for this repository.

Once this pull request is merged, builds can be downloaded at: http://cirelease.nulldev.xyz/mmn-build (no builds there yet obviously)

NOTE TO RAULHAAG: Once this pull request is merged, I will give you the FTP username and password for the host and instructions about how to set the environment variables. (Or you are welcome to use your own host for the builds)

### CODE REVIEW

**Comment by raulhaag** [comment]
it's ok the line 25?

**Comment by null-dev** [comment]
Oh sorry, I'll fix that. the line can be removed entirely anyways.

**Comment by null-dev** [comment]
Oh, it says "The Travis CI build failed" because of a problem in your master branch. You are missing a drawable.

The exact logs can be seen here: https://travis-ci.org/null-dev/MiMangaNu

**Comment by null-dev** [comment]
Can I have your email, I will email you the FTP credentials...

**Comment by raulhaag** [comment]
i send you an email :+1:

**Pull request merged**
