### PR TITLE
Version updates for build and KissManga fixing

### PR DESCRIPTION
**Pull request by tempura-san**

### CODE REVIEW

**Comment by raulhaag** [comment]
merged, i don't know if ducktape correct the big footprint if not i go  to revert (sorri late)

**Comment by tempura-san** [comment]
About duktape - for me it was working fine. Didn't notice (tbh also did not check for) an increased footprint.

**Comment by tempura-san** [comment]
@raulhaag: The last commit fixes #554 - but I do not know the reason why the removal of chapter parts was introduced back in 2015 by you. :sweat_smile: For the mentioned issue it will remove the backtick in the URL and thus lead to the described problem (as the URL becomes a 404).

**Comment by raulhaag** [comment]
@tempura-san really don't remember why, thanks and meging

**Pull request merged**
