### PR TITLE
detect tag on japscan

### PR DESCRIPTION
**Pull request by Zykino**
log is:
[...] I/ZYKILOG: <span class="us"> (RAW)</span>

### CODE REVIEW

**Comment by Zykino** [comment]
THIS IS NOT FINAL !
I achieve getting the "tags", now I have some architectural knowledge of the application needed.

How do I stock the tag in the DB?
Do I pass it to the chapter constructor?
Do I pass it to `chapter.addChapterFirst(manga);` ?

I need to store in DB, compare to DB, refresh info if different.

Do I stock the class list/text only or the full tag?

**Comment by tempura-san** [comment]
I am not sure what your goal is - could you give an example/use case?

You could try to store it in the "extra" information for a chapter (arbitrary `String` set via  `Chapter.setExtra`, JapScan plugin does not use this field yet, so it is free to use) - this should be saved in the DB. Otherwise you would need to change the DB schema, which I would personally avoid if possible.

**Comment by Zykino** [comment]
So in JapScan they upload a "RAW" version
MiMangaNu load it (receive notification)
Have the title with "Scan OnePiece 883 VF : Attention: RAW" (for example)
Later they update it with US version and I have a similar thing (title of the chapter in english or other)
Then they finally upload a french version.

I don't have the notification for the updated version.
The title stay in RAW/English.

Since extra is not used I may use it (as long as it's self to use).
I'll also need to find a way to enter the loop in a more elegant way than `loadMangaInformation(manga, true);`

**Comment by tempura-san** [comment]
In that case, I would override `searchForNewChapters` in `ServerBase`. This is the function which is called whenever new chapters are searched for. This could take into account the changed suffixes for the chapters.
It is also responsible for creating the notification - so take a look in the code and see what you would need to change for JapScan to implement your use case.
BTW: This also takes case of a proper call to `loadMangaInformation`.

**Pull request closed without merging**
