### PR TITLE
Small fixes and improvement of code (a little)

### PR DESCRIPTION
**Pull request by Johndeep**
* reading and finishing L2R mode will finally set chapter as "READ" properly
* replace onProgressUpdate() with publishProgress() in doInBackground methods, this will prevent random crashes, as calling a main method from thread can be problematic, http://stackoverflow.com/questions/9719234/android-calling-the-methods-on-ui-thread-from-asynctask-doinbackground-method
* some strange line wrapping is fixed (only for readability)
* set color for "READ" a little more dark

### CODE REVIEW

**Comment by Johndeep** [comment]
Don't be alarmed that I change one color, it's only because I tried to play around, in preparing for an optional dark theme, and saw the "already read" color is not easy to see, that's all.

**Comment by Johndeep** [comment]
Second wave of commit only re-translation, hopefully now more correctly.

**Comment by Johndeep** [comment]
I hope to not offending raulhaag or anybody with further Spanish to English translation. It's just faster this way to read and search around the code. Maybe for others too.

**Comment by raulhaag** [comment]
No problem whit the traslation i go to merge and test

**Comment by raulhaag** [comment]
image
again R2L, L2R changed

**Comment by Johndeep** [comment]
Hmm, did I change it? If so, then sorry, I'm confused about this myself, please correct them, maybe it was due the order in the preference that I changed it.

**Pull request merged**
