### PR TITLE
Follow-up of #461

### PR DESCRIPTION
**Pull request by tempura-san**
This is an update for #461.

@raulhaag: #461 introduced an issue... By not removing the newline characters from the HTML, some matches will now fail - even if `Pattern.DOTALL` is used. The option implies to treat newlines as regular characters. Which means, they still represent a character. If this is not accounted for, the match will fail (e.g. see `RawSenManga`).

So basically each server needs to be tested... I have written up some test procedure in the JavaDoc part of `ServerBase`.

As of now, these servers have been tested by me according to the procedure. I will continue and rework the other classes as well, but it will take some time.

- MangaHere
- MangaTown
- RawSenManga
- JapScan
- KissManga
- MangaEden
- MangaStream
- mangapanda
- mangareader.net
- Taadd
- ReadMangaToday
- MangaFox
- MangaEdenIt
- SubManga
- MangaKawaii
- LeoManga
- Kumanga
- Mangapedia
- NineManga
(NineManga and its subdomains work as well, but image loading is currently defunct. see comment on #461)

**Until then, there may be potential regressions, so please do not push a new release until the servers are tested ok. Otherwise users will start complaining about the servers not working.**

This pull request also includes improvements for using the `Manga` and `Chapter` classes as they clean up the strings (HTML to string, unescaping of HTML) passed via their setters themselves. This reduces the code in the server part and makes it more readable.

Some documentation update and further annotations were added.

### CODE REVIEW

**Comment by raulhaag** [comment]
hi about ninemanga, it is checking if you have the utmz google analytics generated cookie generate via javascript, if not this ban you about 15 min (by ip), also accept header can be needed but not confirmed

**Comment by tempura-san** [comment]
Hello, thank you - I haven't had a look at it, as I still focus in getting all the servers reworked and tested. Was this cookie stuff already integrated at some point in time? If yes, then I could take it over.

**Comment by raulhaag** [comment]
here is the needed mod for the base server 
```java
    private static String cookie = "";

    private static void generateNeededCookie(){
        cookie = "__utmz=128769555."+ (System.currentTimeMillis()/1000) +".1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); ";
    }
    public Navigator getNavigatorWithNeededHeader() throws Exception {
        if(cookie.isEmpty()){
            generateNeededCookie();
        }
        Navigator nav = new Navigator(context);
        nav.addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0");
        nav.addHeader("Accept-Language", "es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3");
        nav.addHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
        nav.addHeader("Cookie", cookie);
        return nav;
    }

**Comment by tempura-san** [comment]
Thank you - I'll patch it in today. Also, there are not much servers left to check, so I expect to be done by the end of the week.

**Comment by tempura-san** [comment]
@raulhaag I can confirm, that NineManga is working again with the cookie. Thank you!

**Comment by tempura-san** [comment]
@raulhaag Could you please check if MyMangaIo is working for you? It seems that they check the originating request and display some image about stealing their bandwidth. I guess a referer is needed fo this but I am unsure how to add this properly.

**Comment by tempura-san** [comment]
This last commit is the rework, which makes the page image links at least functional again, but the app will fetch the generic image only, whilst a desktop browser works properly.

**Comment by raulhaag** [comment]
@tempura-san  about mymangaIO images have anti hot link referer needed is set as default let me a time and i go to check how they made it.
Tomorrow i go to read all the commits and check, then test it until the weekend and if every is ok make a release

**Comment by raulhaag** [comment]
about the ninemanga fix is only for this server becuase first value is the id od the server but don'yt worry i wil change this, i read a fixme in the todo, i go to merge and do that, tanks for all the rework and cleaning

**Comment by tempura-san** [comment]
Thanks! You're welcome - as always. Five servers are still open for rework. I will add them to my next pull request.

**Pull request merged**
