### PR TITLE
Database: create backup before upgrade

### PR DESCRIPTION
**Pull request by tempura-san**

### CODE REVIEW

**Comment by raulhaag** [comment]
hi @tempura-san, sisnce i read about this i'm thinking in this scenary  1st atemp error on update and the database get backup, all go ok, 2nd atemp the backup is replaced by the the erroneous database overwrite the backup and then we have the same problem, solution atemp is at start a database update check if database.(update version name).bak don't exist create a copy with the not updated database otherwise leave as it

**Comment by raulhaag** [comment]
@tempura-san about notif on update i have an idea just plant a flag at on upgrade start sorrounded by try catch finally deactivating this flag and on get db method make a loop whith thread sleep arround 5 sec in a do while until the upgrade is finishe

**Comment by tempura-san** [comment]
@raulhaag Hi and thank you for your input - I have changed the backup to be created only once. Also the backup is named according to the old version like this `mangas.db.<oldVersion>.bak`.
I was assuming, that once `onUpgrade` is called, the database could be opened properly - i.e. it is not defective. Not sure if this is always true though. The defensive approach of yours looks more promising I guess :smile: 

The second hint of yours I have yet to look into. Nicest thing would be to use the splash screen. A single line of text below the logo would be sufficient to indicate this. But the background is just a style without content - and as I said, I am not too deep into Android. Nonetheless I see what I can figure out.

I was also thinking of adding a button in the preferences to restore the latest database backup - if available. This is meant for user who don't know how to restore the database manually.

**Comment by raulhaag** [comment]
o go to see what i can do, but i having a idea ;-)

**Pull request merged**
