### PR TITLE
MangaTown: remove workaround for 503 - no longer needed

### PR DESCRIPTION
**Pull request by tempura-san**
~~This is the same solution as for MangaTown and works for me.~~

~~If more servers switch to the same kind of protection, it would be good to consider creating some kind of generic functionality for throttling all servers (e.g. also adding some amount of randomness).~~

Fixed by 7de8901.

### CODE REVIEW

**Comment by raulhaag** [comment]
i think the best way to aproach it is a network interceptor for okhttp with a reatry policy count on this kind of error

**Comment by tempura-san** [comment]
Sounds reasonable. Then the workaround in MangaTown could be removed as well.

**Comment by raulhaag** [comment]
check last commit if work for you

**Comment by tempura-san** [comment]
Do you mean d504931bab11b281500f5ed88f95051e945b4b11? This commit is not related to the 503 response - or do I miss anything?

**Comment by raulhaag** [comment]
forget push, https://github.com/raulhaag/MiMangaNu/commit/7de8901571ab9145d6deeb85aeb983cc188f391e

**Comment by tempura-san** [comment]
I have tested downloading a full Manga from MangaHere and MangaTown (with my workaround reverted). Both were working properly - no error was issued during downloading.
I have now added a commit to revert the MangaTown workaround to this PR.

**Comment by tempura-san** [comment]
Thank you! :+1:

**Pull request merged**
