### PR TITLE
Server improvements

### PR DESCRIPTION
**Pull request by Johndeep**
* improved German servers and clean up source
* small other fixes

### CODE REVIEW

**Comment by Johndeep** [comment]
Okay, last thing for now, waiting for release :smiley:

**Comment by raulhaag** [comment]
Finishing the db move almost there but testing in multiple virtual machines

**Comment by raulhaag** [comment]
check the last commit try to test on devices whit the old version installed

**Comment by raulhaag** [comment]
realease changelog go to be hard to do :-P

**Comment by Johndeep** [comment]
Many changes huh :smile: 
Did you tested the database in RELEASE?

Because of these line in SQLOpenHelper.java

```
private SQLiteDatabase getDatabaseLocked(boolean writable) {

...

if (DEBUG_STRICT_READONLY && !writable) {
    final String path = mContext.getDatabasePath(mName).getPath();
    db = SQLiteDatabase.openDatabase(path, mFactory,
    SQLiteDatabase.OPEN_READONLY, mErrorHandler);
} else {
    db = mContext.openOrCreateDatabase(mName, mEnableWriteAheadLogging ?
            Context.MODE_ENABLE_WRITE_AHEAD_LOGGING : 0,
            mFactory, mErrorHandler);
}
...
```

I'm afraid the database path works only in DEBUG, but **not** in RELEASE.

I can test this, but it has to work in RELEASE too. If this fails, we could write a "database import/export" menu.

**Comment by Johndeep** [comment]
It seems to work, I simulated the old version by copying the new database to data/data.
Nice, now the cache _and_ database are in one place!

**Pull request merged**
