### PR TITLE
fixed ip and improved search

### PR DESCRIPTION
**Pull request by Johndeep**
- removed IP dependency (no IP necessary)
- improved search functionality, now words are not encoded and single results are shown correctly
- and translated some spanish term to english, by the way

### CODE REVIEW

**Comment by Johndeep** [comment]
Here we are, the fix, whoever wrote Navegador.java (spanish for browser?), he did a good job adding some features, which is still not used anywhere but made my changes much easier.

**Comment by raulhaag** [comment]
i wrote the browser for other apps to easy get source of web pages, and now i using this for a lot of test

**Comment by raulhaag** [comment]
when i get at go to merge

**Comment by Johndeep** [comment]
Do I have to do something for merging?

**Comment by raulhaag** [comment]
only pull request, the merge need to be performed by the owner

**Comment by Johndeep** [comment]
So.. what exactly am I suppose to do? (sorry really the first time in github)

**Comment by raulhaag** [comment]
you can pull request like until now then wait for the merge

**Comment by Johndeep** [comment]
Hmm, sorry, I think I will do some more improvements before I make a pull request.

**Pull request closed without merging**
