### PR TITLE
Fix internet detection

### LINKED ISSUE #443: App do not want to download even if there is connection
I access internet by WIFI and data.
Often, instead of verifying if there is new chapters to download, MiMangaNu wait for me to switch (on or off) the WIFI.
And I mean a manual switch (going in or out of WIFI range doesn't trigger the search).

The problem is when I'm connected to internet and try to download. MiMangaNu often say me I have no connection until I switch the WIFI button.

### PR DESCRIPTION
**Pull request by Zykino**
I open it so we can talk about it, maybe some commits need to do more or be reverted. This is mainly to resolves #443 and I tried my best to understand the code around the message.

Also not an Android dev at core so how can I test the App on my phone AND keep the official one from F-Droid?

### CODE REVIEW

**Comment by raulhaag** [comment]
Hi disable internet state detection is a more general like don't check any internet state (wifi included) so this isn't the final objetive of the function

**Comment by Zykino** [comment]
In this case when the option is disabled the "only wifi" option should be disabled/greyed.

I don't really understand what your option does except keeping in mind the internet state of "last time checked". My phone have an option to disable WIFI when the screen is off, how does it works with people telling only WIFI and your option?
- MiMangaNu see a WIFI connection
- Phone is locked (WIFI is shutted down)
- MiMangaNu try to update the manga list, respond there is a WIFI connection when there is not anymore
- Register there is no connection?
- Next time the phone is unlocked and WIFI is up again the connection is still marked as not connected?

I'm curious about what you are trying to do with this option because the code is confusing me a bit.

**Comment by raulhaag** [comment]
first option go to disable all internet connection checks:
    in this case the app try to connect and if there is any kind of connection, it is used otherwise it give timeout or connection errors and stop.
second only wifi:
    this check if wifi is aviable otherwise stop
last option:
    any connection data / wifi it will check internet is working otherwise stop

**Comment by raulhaag** [comment]
about greyed is true there is an option depends on the xml that need to be added

**Pull request closed without merging**
