### PR TITLE
improve MemCache, code clean up

### PR DESCRIPTION
**Pull request by Johndeep**
Haha :sweat_smile:, not the last update it seems.

* lruCache is safer, easier to maintain, maybe reduce crashes and prevent some strange image loading blinking.
* replace some "sp" to "dp", because sp should be used for text, not layout.

### CODE REVIEW

**Comment by Johndeep** [comment]
Here another small improvements, should make loading image much smoother. Maybe it can reduce some more crashes.

And yes, the changelog will be really big this time :smile:

**Comment by Johndeep** [comment]
Last commits are clean ups and readability. Should make code easier to read and understand.

**Comment by Johndeep** [comment]
Latest commits are for better readability and better understanding.

**Comment by raulhaag** [comment]
last merge after release, test on release of db go well :-)

**Comment by Johndeep** [comment]
You mean last merge _before_ release ;-)
And yes, many new things are now implemented. Let us see, what feedback we'll get after release.

**Pull request merged**
