### PR TITLE
Unit test implementation and fixes

### PR DESCRIPTION
**Pull request by tempura-san**
This PR is the current state of my efforts in delivering a proper unit test using Robolectric (and also doing fixes along the way).

Note, that the tests will not work without a workaround in the `Navigator` class in the `getTrustManagers` method:

```java
// uncomment for device-based testing
/*
KeyStore keyStore = KeyStore.getInstance("AndroidCAStore");
keyStore.load(null, null);
*/
// uncomment for host-based testing
KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
keyStore.load(new FileInputStream(
        System.getProperty("java.home") + "/lib/security/cacerts"), null);
```

Class shadowing shall be used to prevent need for this workaround. The related discussion for Robolectric can be found [here](https://github.com/robolectric/robolectric/issues/1518).

### CODE REVIEW

**Comment by tempura-san** [comment]
@raulhaag This PR is now ready for integration. It contains several fixes for some servers as well.

MangaStream really needed several fixes to work properly.

Now unit testing is available for most of the servers (which do not use Duktape, these still need to be tested on the device) directly on the development machine, which should keep test times low and also enable fast feedback on the state of the servers.

**Comment by raulhaag** [comment]
sorry no time, this weekend i go to read all and confirm the merge

**Comment by tempura-san** [comment]
No problem - sorry for this much changes. :sweat: 
I am looking forward to your review of what I have done. I believe this will be a good foundation for more reliable testing of the server scrapers (and it could of course be extended to one's heart's content).

**Comment by raulhaag** [comment]
can't make test works on windows 
WARNING: No manifest file found at .\..\app\src\main\AndroidManifest.xml.

**Comment by tempura-san** [comment]
Is the working directory set up properly? There seems to be a bug in Android Studio. See http://robolectric.org/getting-started/ - although it says for Linux and Mac users... (BTW I am on Linux at my end)

**Comment by raulhaag** [comment]
ok just update to android studio 3 and gradle 4.0.2 ana remove the manifest line and added the changes for android studio 3 and work, but it force me to remove action on broadcast receiver i need wait for test if still works, may be a migration to job scheduler go to be needed

**Comment by tempura-san** [comment]
Strange. For me it was working with Android Studio either 2.3.3 and 3 - without having to update Gradle.
Anything I can support with?

**Comment by raulhaag** [comment]
i just added the
<intent-filter>
and now is working all ok

**Comment by tempura-san** [comment]
Not that you mention it, there was some warning in the manifest. But as I am not so deep into Android, I kept it as it was.

**Pull request merged**
