### PR TITLE
All network communication now uses OkHttp.

### LINKED ISSUE #176: Migrate Network Code to OkHttp?
I would highly recommend migrating all network code to OkHttp. I acknowledge that libraries increase APK sizes however the current network code is not very failsafe and does not work very well on trippy connections (like mine). It would reduce your network code by a couple hundred lines too :+1:. Most apps that access the internet these days use OkHttp anyways...

If this is ok, I can start working on it right away.

P.S. Also, I am looking at the parsing code and I just really, really want to stick in the JSoup library and parse it normally. As many of you know (from here: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags) that parsing HTML with regex is just a plain bad idea so I think a real HTML parser would do use a lot of good :). I think I can do this too if you are ok with it.

P. P. S. I've already tested adding the Jsoup and OkHttp libraries and in total, APK size went up by only about 0.3mb.

### PR DESCRIPTION
**Pull request by null-dev**
I've managed to migrate everything to OkHttp! (That was fast).

Resolves #176 (obviously).

Programming wise, it looks like everything is ok but I HAVE NOT TESTED ANY SOURCES YET!

<b>I NEED TESTERS, WE NEED TO CONFIRM THAT EVERYTHING WORKS USING THE NEW NETWORK CODE.</b> If anybody has time, it would be nice if you could grab the latest ~~travis-ci~~ build for this pull request <a href="http://files.nulldev.xyz/Misc/RandomStuff/mmn-okhttp-test.apk">here</a> and test your favourite servers to see if downloading and everything works properly.

Post here if something is broken.

~~DO NOT MERGE THIS YET, SOME SOURCES APPEAR BROKEN~~

### CODE REVIEW

**Comment by raulhaag** [comment]
i go to test

**Comment by raulhaag** [comment]
response.body().string().replaceAll("\n",""); can solve almost all

**Comment by null-dev** [comment]
OK thanks, I'll add that in once I get back from school.

**Comment by raulhaag** [comment]
correction 
return response.body().string().replaceAll("(\n|\r)",""); and appear all working

**Comment by null-dev** [comment]
Thanks raulhaag for the fix. Everything looks like it's working now. If there are any more problems, just post here but otherwise, it looks good for merge!

**Pull request merged**
