### PR TITLE
Database cleaning

### PR DESCRIPTION
**Pull request by Johndeep**
* changed file path of database of manga to own folder. This will finally allow us to do a "backup" of the folder without losing by uninstalling the app. Even if we uninstall the app and install it again the database is untouched. WARNING, if user already has a database before next version of app, then the user has to move the database from data/data into MiMangaNu/ folder!!
* The database will create a _mangas.db_ and a _mangas.db-journal_ file, first one is the data itself, second one ensures save rollback of transactions..
* clean up Lazyload, refactored quite a bit, renamed and commented, so it becomes clearer, but functionally, nothing is really changed.

### CODE REVIEW

**Comment by Johndeep** [comment]
Here we are, even with SQLHelper it is possible to choose a custom path, it this case, I choose to save it into the manga folder.

**Comment by raulhaag** [comment]
i make a time to read and think about the db 
- not all user can copy this (not root, no know how, etc) they go lost their data
how to solve this in easy way...
there is a method called when the database was upgraded, that is the moment when the program need to run a task to copy the db to sd directory

**Comment by raulhaag** [comment]
public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
if(newVersion >= v && !dbFileOnSd.exist()){
copy db to sd folder
}
}
something like that

**Comment by Johndeep** [comment]
Tell me sooner that you don't like the "manually move data" stuff ^^"
Well, I try to do what I can.

**Comment by Johndeep** [comment]
Okay, I decide to undo this database feature in the next commit, so please wait a little longer.
1. This only works in debug mode (chaos...)
2. We could try to make an import/export function instead, but this won't come in this pull request.

Instead, I'm working on replacing the colorpickercollection with an own fast colorpicker preference, hope you'll like this. I'll also improve the directory look and feel.

Stay put!

**Comment by raulhaag** [comment]
wait, i have the code to copy on upgrade from an old app only i need found where i leave the source :-P

**Pull request closed without merging**
