### PR TITLE
Added Mangakakalot

### PR DESCRIPTION
**Pull request by juh9870**
I wasn't able to run tests cuz problems with keystore

### CODE REVIEW

**Comment by juh9870** [comment]
#704

**Comment by raulhaag** [comment]
the mimanganu keystore use mimanganu in all fields, this afternooni go to check and merge

**Comment by raulhaag** [comment]
Hi while testing same mangas give error on load manga (manw) information and the server response is a redirect script to manganelo (example tales of demosn and gods)

**Comment by juh9870** [comment]
lot of mangas redirect to manganelo, but manganelo use exactly same HTML formatting for mangas as mangakakalot, so they grabbed just fine.
About not working ones, please give me some names so i can try to fix then

**Comment by raulhaag** [comment]
manganelo an did not recognice chapters author and sumary
in example: from app you get the https://mangakakalot.com/manga/hyer5231574354229 tales of demosn and gods instead of https://mangakakalot.com/manga/hyer5231574354229 the first return a small html with a redirection script

**Comment by juh9870** [comment]
Hmm, in this case it might be better to add manganelo as separate source

**Comment by raulhaag** [comment]
i think is better add only manganelo just beacuase is the main server,  mangakakalot is only other "face"

**Pull request merged**
