### PR TITLE
Fixed some findings

### PR DESCRIPTION
**Pull request by tempura-san**
* MangaFox has changed its host, so the genre extraction did not work.
* For `FilteredNavigation` when displaying filtered search results, clicking a Manga and returning to the previous view could add the result set another time if the object is not constructed via new (due to `addAll` being called). This has been changed to a simple assignment.
* `SingleDownload` should save an error image in case the download fails for some reason. In order to locate the asset, the `DownloadPoolService` instance is used. As this might be **null** when the error image is to be located, the error image is not loaded, but the spinning circle remains. To counter this, a `Context` reference is passed down.
* Warnings were fixed if possible.

### CODE REVIEW

**Comment by raulhaag** [comment]
about the fitered navigation, you change addall to adapter for replace the current data

**Comment by tempura-san** [comment]
Yes, this was intended - see the second point in the description.

**Comment by raulhaag** [comment]
two cons about this can go back on list and if you have a small screen its start loading next page again because the displacement is already set

**Comment by tempura-san** [comment]
Then would it be better to only add only Manga not yet in the list? So create the intersection between the already listed ones and the ones to be added, and add the remaining only?

**Comment by raulhaag** [comment]
when you change the filter the list is new, when you pass from a page to another its add the new results to the actual list, the repeated only happends when you order is set on "last updates" and a new update is published (its not so ussual)

**Comment by tempura-san** [comment]
For me it was reproducible:
* set a Manga filter where the resulting list is less than one screen long (e.g. MangaFox: 'Horror' & 'Harem' IIRC)
* click on a Manga to open the 'Details' view
* return to the filtered list by pressing 'Back' (do not change the filter)
* click on a Manga to open the 'Details' view
* return to the filtered list by pressing 'Back'
* the list of results is added once more at the end (so the result is shown twice)

**Comment by raulhaag** [comment]
Check this video it's explain how it work on cellphone
https://streamable.com/lsxi5

**Comment by tempura-san** [comment]
OK, got it. Thanks for showing! I have only my 7" tablet to test...
If the result is more than one page, only one page of scrolling is shown. I'll see into it tomorrow.

**Comment by tempura-san** [comment]
I have reordered the commits for the problematic one to be last.

Also I have changed the approach: Keep track of which pages are already loaded (`top_page`) and only add new results if a new page is requested (`req_page > top_page`). The only downside is, that `req_page` must start at 1 and must increment by 1. But for the filtered view this should be good guess.

So this works for me, question is if it works for you as well? 😄

**Comment by raulhaag** [comment]
merging 👍

**Comment by tempura-san** [comment]
Guess it is working then. 😄 👍

**Pull request merged**
