### PR TITLE
improved french translation

### PR DESCRIPTION
**Pull request by M2ck**

### CODE REVIEW

**Comment by M2ck** [comment]
@Dostoi, are you agree with these corrections?

**Comment by Dostoi** [comment]
Yes it's great.
The only one bugging me is "Cacher les images téléchargées" because you don't know from where they're going to be hided.

**Comment by M2ck** [comment]
I've removed this info to avoid a repeat because it is already given in the option title, [see screenshot](https://dl2.pushbulletusercontent.com/IwiujbQsysCEJFIRJBeWvvUn5yOlmWhZ/Screenshot_2015-11-28-12-43-00.png).

**Comment by Dostoi** [comment]
Ho ok then, it's better this way

**Pull request merged**
