### PR TITLE
UI Tweaks and translation fixes.

### PR DESCRIPTION
**Pull request by TheSniperFan**
* Added new icon for "New Manga" notification that fits the material design better
* Added various missing translations
* Fixed color preview clipping in settings
* Allow unescaping various HTML characters so that synopses look better
* New way of visually differentiating between read, unread and reading mangas
* German translation

### CODE REVIEW

**Comment by raulhaag** [comment]
Beleave or not the "New way of visually differentiating between read, unread and reading mangas" had planned to do almost the same, only taxes to use the secondary color for reading

**Comment by TheSniperFan** [comment]
I see. :-)
I just did it because it was hard to see. There just wasn't enough contrast.

I'm thinking about what to do next. Say, have you ever considered
translating the code? Making the classes, etc. English?
I have such a hard time, because I'm from Germany and don't speak Spanish...
It makes it hard to contribute.

**Comment by raulhaag** [comment]
i know the code have part in english and others in spanish and that isn't good but in the moment to code a side of me says "why are you coding in english if you speak spanish" but now i have an excuse :-P.
i go to see what i can do.

**Comment by TheSniperFan** [comment]
Well, I'm not from an English speaking country either.
Coding in English is a standard because every programmer understands it.

I'll see how I can help with the refactoring, when I have some time. ;-)

**Comment by raulhaag** [comment]
ok, thank for all.

**Pull request merged**
